spring:
  application:
    name: front
  security:
    oauth2:
      client:
        provider:
          baeldung-keycloak:
            issuer-uri: http://localhost:8080/realms/baeldung-keycloak
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
server:
  port: 8082
gateway:
  url: http://localhost:8761
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
