spring:
  application:
    name: notes

server:
  port: 8091

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${eureka.instance.hostname}:8761/eureka/}
#server.port=8091
#eureka.instance.hostname=notes
#spring.application.name=notes
#
#spring.datasource.url=mongodb://localhost:27017/medilabo
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=medilabo
#
#eureka.instance.prefer-ip-address=true
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.client.fetch-registry= true
#eureka.client.register-with-eureka= true
