server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: patients
        uri: http://192.168.1.95:8090
        predicates:
          - Path=/patients/**
      - id: notes
        uri: http://192.168.1.95:8091
        predicates:
          - Path=/notes/**
      - id: risk-report
        uri: http://192.168.1.95:8094
        predicates:
          - Path=/risk-report/**
  config:
    import: optional:configserver:https://github.com/vlav98/medilabo-config

eureka:
  instance:
    hostname: 192.168.1.95
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.95:8761/eureka/

logging:
  level:
    com.netflix.eureka: INFO
