server:
  port: 8761
spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:8088"
    activate:
      on-profile: docker
  cloud:
    gateway:
      routes:
        - id: patient
          uri: http://medilabo-patients:8090
          predicates:
            - Path=/medilabo-patients
        - id: note
          uri: http://medilabo-notes:8091
          predicates:
            - Path=/medilabo-notes
        - id: risk-report
          uri: http://medilabo-risk-report:8094
          predicates:
            - Path=/medilabo-risk-report
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
