spring:
  application:
    name: medilabo-risk-report
server:
  port: 8094
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
